//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Emlak_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEMLAK_DETAY
    {
        public int ILAN_DETAY_NO { get; set; }
        public string OZELLIK { get; set; }
        public Nullable<bool> VARYOK { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual TBLEMLAK TBLEMLAK { get; set; }
    }
}
