//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Emlak_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEMLAK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLEMLAK()
        {
            this.TBLEMLAK_DETAY = new HashSet<TBLEMLAK_DETAY>();
            this.TBLRESIM = new HashSet<TBLRESIM>();
        }
    
        public int ILAN_NO { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LNG { get; set; }
        public string ILAN_HTML { get; set; }
        public string ILAN_ICERIGI { get; set; }
        public string ILAN_BASLIGI { get; set; }
        public Nullable<System.DateTime> ILAN_TARIHI { get; set; }
        public int SATILIK_KIRALIK { get; set; }
        public Nullable<int> BINA_YASI { get; set; }
        public Nullable<int> BULUNDUGU_KAT { get; set; }
        public Nullable<int> TOPLAM_KAT_SAYISI { get; set; }
        public Nullable<int> ISITMA_TIPI { get; set; }
        public Nullable<int> FIYAT { get; set; }
        public Nullable<int> SORUMLU_ID { get; set; }
        public Nullable<int> M2 { get; set; }
        public string ODA_SAYISI { get; set; }
        public string KONUMU { get; set; }
        public Nullable<bool> ONE_CIKAN { get; set; }
        public Nullable<int> EMLAK_TIP_ID { get; set; }
        public Nullable<bool> FIYATI_DUSEN { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEMLAK_DETAY> TBLEMLAK_DETAY { get; set; }
        public virtual TBLEMLAKTIP TBLEMLAKTIP { get; set; }
        public virtual TBLSORUMLU TBLSORUMLU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRESIM> TBLRESIM { get; set; }
    }
}
