//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Emlak_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICI
    {
        public int ID { get; set; }
        public string Kullanici_Adi { get; set; }
        public string sifre { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> YETKI_ID { get; set; }
    }
}
