//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Emlak_Sitesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRESIM
    {
        public int ID { get; set; }
        public int EMLAK_ILAN_NO { get; set; }
        public string RESIM_YOLU { get; set; }
        public string ALT_ETIKETI { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<byte> SIRA_NO { get; set; }
    
        public virtual TBLEMLAK TBLEMLAK { get; set; }
    }
}
